general:
  language: zh-CN #en-US # It will determine bing search market and LLM prompt language. en-US / zh-CN / it-IT / fr-FR / de-DE / es-ES / ja-JP / ko-KR / pt-BR / ru-RU / etc.
source_service:
  is_use_source: true # grounded or not grounded. If not grounded, meaning just Q&A via LLM
  is_enable_bing_search: true
  is_enable_doc_search: false
  doc_search_path:
  bing_search:
    end_point: https://api.bing.microsoft.com
    subscription_key: "get subscription key from https://azure.microsoft.com/en-us/try/cognitive-services/?api=bing-web-search-api"
    result_count: 3
    sentence_count_per_site: 20
    text_extract: trafilatura # beautifulsoup / trafilatura
llm_service:
  provider: openai # openai/goose_ai
  openai_api:
    api_key: "get api key from https://beta.openai.com/"
    model: gpt-4-1106-preview # default
    max_tokens: 4096
    temperature: 0.2
    top_p: 1
    prompt:
      prompt_token_limit: 1500
    stream: true
  goose_ai_api:
    api_key:
    api_base: https://api.goose.ai/v1
    # https://goose.ai/docs/models
    model: gpt-neo-20b
    max_tokens: 100
cache:  # .cache result for efficiency and consistency
  is_enable:
    web: true
    bing_search_website: true
    bing_search_website_content: true
    openai: false
    gooseai: false
  path: .cache
  max_number_of_cache: 300
frontend_service:
  prompt_examples:
    col1_list:
      - Alpaca lora
      - what is new for gpt4?
      - Why Llama LLM model is so popular?
      - Why did SVB collapsed?
      - End of FTX
    col2_list:
      - digital twin有哪些用处
      - 아가동산사건의 문제가 뭐야
      - Hoe maak ik pasta
      - 日本国憲法は誰が作ったのか？
      - Comment gagner de l'argent

